// Generated by /tools/gen.js
import module_cat from './cat.js'
import module_cd from './cd.js'
import module_cp from './cp.js'
import module_echo from './echo.js'
import module_ls from './ls.js'
import module_mkdir from './mkdir.js'
import module_mv from './mv.js'
import module_putercmd from './putercmd.js'
import module_rm from './rm.js'
import module_tail from './tail.js'
import module_touch from './touch.js'

export default {
    "cat": module_cat,
    "cd": module_cd,
    "cp": module_cp,
    "echo": module_echo,
    "ls": module_ls,
    "mkdir": module_mkdir,
    "mv": module_mv,
    "putercmd": module_putercmd,
    "rm": module_rm,
    "tail": module_tail,
    "touch": module_touch,
};
