// Generated by /tools/gen.js
import module_cat from './cat.js'
import module_cd from './cd.js'
import module_changelog from './changelog.js'
import module_clear from './clear.js'
import module_cp from './cp.js'
import module_dcall from './dcall.js'
import module_echo from './echo.js'
import module_help from './help.js'
import module_jq from './jq.js'
import module_ls from './ls.js'
import module_mkdir from './mkdir.js'
import module_mv from './mv.js'
import module_neofetch from './neofetch.js'
import module_printenv from './printenv.js'
import module_putercmd from './putercmd.js'
import module_pwd from './pwd.js'
import module_rm from './rm.js'
import module_sample_data from './sample-data.js'
import module_tail from './tail.js'
import module_touch from './touch.js'

export default {
    "cat": module_cat,
    "cd": module_cd,
    "changelog": module_changelog,
    "clear": module_clear,
    "cp": module_cp,
    "dcall": module_dcall,
    "echo": module_echo,
    "help": module_help,
    "jq": module_jq,
    "ls": module_ls,
    "mkdir": module_mkdir,
    "mv": module_mv,
    "neofetch": module_neofetch,
    "printenv": module_printenv,
    "putercmd": module_putercmd,
    "pwd": module_pwd,
    "rm": module_rm,
    "sample-data": module_sample_data,
    "tail": module_tail,
    "touch": module_touch,
};
