// Generated by /tools/gen.js
import module_ai from './ai.js'
import module_cat from './cat.js'
import module_cd from './cd.js'
import module_changelog from './changelog.js'
import module_clear from './clear.js'
import module_cp from './cp.js'
import module_dcall from './dcall.js'
import module_echo from './echo.js'
import module_grep from './grep.js'
import module_help from './help.js'
import module_jq from './jq.js'
import module_login from './login.js'
import module_ls from './ls.js'
import module_mkdir from './mkdir.js'
import module_mv from './mv.js'
import module_neofetch from './neofetch.js'
import module_printenv from './printenv.js'
import module_printhist from './printhist.js'
import module_pwd from './pwd.js'
import module_rm from './rm.js'
import module_rmdir from './rmdir.js'
import module_sample_data from './sample-data.js'
import module_tail from './tail.js'
import module_test from './test.js'
import module_touch from './touch.js'
import module_txt2img from './txt2img.js'
import module_usages from './usages.js'

export default {
    "ai": module_ai,
    "cat": module_cat,
    "cd": module_cd,
    "changelog": module_changelog,
    "clear": module_clear,
    "cp": module_cp,
    "dcall": module_dcall,
    "echo": module_echo,
    "grep": module_grep,
    "help": module_help,
    "jq": module_jq,
    "login": module_login,
    "ls": module_ls,
    "mkdir": module_mkdir,
    "mv": module_mv,
    "neofetch": module_neofetch,
    "printenv": module_printenv,
    "printhist": module_printhist,
    "pwd": module_pwd,
    "rm": module_rm,
    "rmdir": module_rmdir,
    "sample-data": module_sample_data,
    "tail": module_tail,
    "test": module_test,
    "touch": module_touch,
    "txt2img": module_txt2img,
    "usages": module_usages,
};
