// Script that generates some of the javascript files
import fs from 'fs';
import path from 'path';

const [directory] = process.argv.slice(2);
const target = path.resolve(process.cwd(), directory);
const outputFile = path.resolve(target, '__exports__.js');

const files = fs.readdirSync(target);

let output = '';
const line = str => {
    output += str + '\n';
}

line('// Generated by /tools/gen.js');

for ( const file of files ) {
    const name = path.parse(file).name;
    if ( name === '__exports__' ) continue;
    line(`import module_${name} from './${file}'`);
}

line('');
line('export default {');

for ( const file of files ) {
    const name = path.parse(file).name;
    if ( name === '__exports__' ) continue;
    line(`    ${JSON.stringify(name)}: module_${name},`);
}

line('};');

fs.writeFileSync(outputFile, output);
